---
- hosts: 172.31.15.225
  become: yes
  tasks: 
  - name: i want to install git
    apt:
      name: git
      state: present 
    tags: gittag
  - name: i want to install tree
    apt:
      name: tree
      state: present
    ignore_errors: True
  - name: i want to install wget
    apt:
      nameddddd: wget
      state: present
    ignore_errors: True
    tags: wget tag