---
- hosts: myubuntu_servers
  become: yes
  tasks: 
    - name: i want to install apache
      apt: 
       name: "{{mywebpacakageonubuntu}}"
       state: present
       when: ansible_os_family =="Debian"
    - name: i want to start instance
      service: 
       name: "{{mywebpacakageonubuntu}}"
       state: started
    - name: i want to install httpd
      apt: 
       name: "{{mywebpacakageonRedHat}}"
       state: present
      when: ansible_os_family =="RedHat"
    - name: i want to start instance
      service: 
       name: "{{mywebpacakageonRedHat}}"
       state: started
      when: ansible_os_family =="RedHat"
      