---
- hosts: mywebservers
  become: yes
  tasks: 
    - name: i want to install apache
      apt: 
       name: apache2
       state: present
      when: ansible_os_family =="Debian"
    - name: i want to start instance
      service: 
       name: apache2
       state: started
      when: ansible_os_family =="Debian" 
    - name: i want to install httpd
      yum: 
       name: httpd
       state: present
      when: ansible_os_family =="RedHat"
    - name: i want to start instance
      service: 
       name: httpd
       state: started
      when: ansible_os_family =="RedHat"
