---
- hosts: 172.31.15.225
  become: yes
  tasks: 
   - name: i want to install three apps
     apt:
        name: "{{ item }}"
        state: present
     loop: 
      - git
      - tree
      - apache2
